import { type FactSheet } from "@terra-oracle/terra-oracle";

/**
 * Sends the Oracle Fact Sheet to Gemini using a direct REST fetch.
 * This bypasses SDK-specific authentication errors like 401.
 */
export async function getAgriAdvisory(factSheet: FactSheet): Promise<string> {
  const apiKey = (import.meta.env.VITE_GEMINI_API_KEY || "").trim();
  
  if (!apiKey) {
    throw new Error("Missing VITE_GEMINI_API_KEY in environment variables.");
  }

  // Use the stable v1 API with the key as a query parameter for maximum compatibility
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

  const payload = {
    contents: [{
      parts: [{
        text: `
          You are an expert agronomist specialized in climate adaptation for the Global South.
          Analyze this field condition report for ${factSheet.crop_name} generated by the Terra Oracle:
          
          ${JSON.stringify(factSheet, null, 2)}
          
          Provide a concise, practical survival strategy for the farmer.
          Structure your response with:
          1. Current thermal risk level.
          2. Immediate 24-hour actions to protect the yield.
          3. One long-term climate tip.
          
          Format the response in clean Markdown. Be encouraging, human, and practical.
        `
      }]
    }]
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error?.message || `API Error: ${response.status}`);
  }

  // Extract text from the candidate parts
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "No advisory generated.";
}
