import { GoogleGenerativeAI } from "@google/generative-ai";
import { type FactSheet } from "@terra-oracle/terra-oracle";

// Initialize the Gemini SDK
const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY);

/**
 * Sends the Oracle Fact Sheet to Gemini to generate expert advisory text.
 * @param factSheet - The raw data returned by @terra-oracle/terra-oracle
 * @returns - Expert advisory text as a string (Markdown)
 */
export async function getAgriAdvisory(factSheet: FactSheet): Promise<string> {
  // Use gemini-3-flash-preview for high-speed, cost-effective reasoning
  const model = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });

  const prompt = `
    You are an expert agronomist specialized in climate adaptation for the Global South.
    Analyze this field condition report for ${factSheet.crop_name} generated by the Terra Oracle:
    
    ${JSON.stringify(factSheet, null, 2)}
    
    Provide a concise, practical survival strategy for the farmer.
    Structure your response with:
    1. Current thermal risk level.
    2. Immediate 24-hour actions to protect the yield.
    3. One long-term climate tip.
    
    Format the response in clean Markdown. Be encouraging, human, and practical.
  `;

  const result = await model.generateContent(prompt);
  const response = await result.response;
  return response.text();
}
