import { GoogleGenerativeAI } from "@google/generative-ai";
import { type FactSheet } from "@terra-oracle/terra-oracle";

// Initialize the Gemini SDK and trim any accidental whitespace from the environment variable
const apiKey = (import.meta.env.VITE_GEMINI_API_KEY || "").trim();
const genAI = new GoogleGenerativeAI(apiKey);

/**
 * Sends the Oracle Fact Sheet to Gemini to generate expert advisory text.
 */
export async function getAgriAdvisory(factSheet: FactSheet): Promise<string> {
  // Switched to gemini-1.5-flash for maximum stability on the public free tier
  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

  const prompt = `
    You are an expert agronomist specialized in climate adaptation for the Global South.
    Analyze this field condition report for ${factSheet.crop_name} generated by the Terra Oracle:
    
    ${JSON.stringify(factSheet, null, 2)}
    
    Provide a concise, practical survival strategy for the farmer.
    Structure your response with:
    1. Current thermal risk level.
    2. Immediate 24-hour actions to protect the yield.
    3. One long-term climate tip.
    
    Format the response in clean Markdown. Be encouraging, human, and practical.
  `;

  const result = await model.generateContent(prompt);
  const response = await result.response;
  return response.text();
}
